server:
  port: 8082


spring:
  application:
    name: mall-mvc
  datasource:
    url: jdbc:mysql://localhost:3306/s-pay-mall?useUnicode=true&characterEncoding=utf-8&serverTimezone=Asia/Shanghai
    password: 1234567890
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  data:
    redis:
      host: 8.130.113.61
      port: 6379
      database: 0
      password: tspkhnNZJR6aXk84

  hikari:
    connection-test-query: select 1
    connection-timeout: 20000
    idle-timeout: 300000
    maximum-pool-size: 5
    minimum-idle: 5


mybatis-plus:
  mapper-locations: classpath:mapper/*.xml

# 支付宝支付 - 沙箱 https://opendocs.alipay.com/common/02kkv7
alipay:
  enabled: true
  app_id: 9021000142691790
  merchant_private_key: MIIEvQIBADANBgkqhkiG9w0BAQEFAASCBKcwggSjAgEAAoIBAQCGKNJE2EJSzW13JCfv3fTrG9KbBYSu6ed5ZsGVBEsUKxhPZlrzXLS910J85tuXpiRWl5eK3JNDYFU9DAV93tobj5RwIRWRSuvryuEay1Zy6Lh0T0V0evz85vn3afrASAJN6x6biWeL1BZcjUmBjJlxywWvM9Vp4tEl/gvIvuWEhZ3JO3RzBX+bJeawKHjMsN7O5chsWc+qwZalHaY8oLPrALnKsbKXIGmlRIHx6wPo+7xZ1/uJqF9SuP7IJx2KIoScxQZUba01SVIkH4CPhYX1KkymJEcv13H027gDfYgZyBgKU55vv2jmunT95rLbMC/dTmCa77ZH7V5iV/SCBoNxAgMBAAECggEAbA+tbm6S3YdCSNkCoh6yDD4Y4W0MdqdJH2w5OQKARvp/VlUnpSZjHxaoI1sAPaJBWs437k3FAFwzzDxGoCBEpjZ8ZeUALkuexApiTubB90Skbmr7ktsNs9eIOFVQ+FgIIyLjQHzovqRSbrIPJx5M6m+RYJHrsKJVvLhoXYYF8TtM/Unk/A5gC+XLNLLSXokYik7C/aQtKS1saHISxqq3/AuHWRBVJdOA4gochhCyTWqaUVTW3uzlb8KeYpYiXZ2NkSAa6wf7J4OFhc6NeA8tSEbRtf6khHbPF6rj2YRMlK/dEeSQ4U22kgn1n9nL2LHi2ouw7wiOhhT0txE26EC2wQKBgQDnORkGKJ8zdSvCNbyeFFyv16eM5LDBLP0DzW74dwaF3KWawY84ggd96576zAluqi2IpDtfVHEDUNCyNkVJMOBU09fF0LfNAOCE64S0eGnrP3/5n2asTf38J+KLXcePS2AnayesFf3OzgMHmaZuMs04yK+HtjS33rDw/gBnVhnAVQKBgQCUiRQzaDzD3SqLtEHhgLxbaQmFW6tBIkDZ47xvnbFPLNBPQdF1apUsaUPEaDe1ujGomqvqHN9Y64CG5RRCtQNcAAeEZLyTuDBT+Zk1x3l3aEPzGPkvPsBcYHgAzhjzlVV7y+B+ORikl54xEsfiLf526d+j50Ovt/UCKGRJXgNirQKBgCIe2+F7xxpp1P5Avce6C39rXG8/JBItmFyiSRjjP5QrXki6/W6CSaa8SWaLC21IMZXzXkuQA2lQ2KsjtQ+65a++3x1y0lyvH3Kd6qRTDJZJdZIZgqY0kCFQpW6ZdSRhJBxNBLqxOBX3cp0BgHzMhFo3yydErPzhIM0/PkIBg6VNAoGAepEO0Ui/c6QJ2pQZFPqE8y0ehSPakfmw59trf/Lw//NrxSr7q1cS1z3ZhLW22sdU+NsA50OB7b8PJMDdUhpKNl1z1oTFs2N2xaSeD2mVyrmH8I53+MtgMhoMjCWFI2Lj0i6vBZkZw5+1Eqt7syDe7MMaHwbTrKkwjOJFtuDUDFUCgYEAwgXCyAQ0Dnr0V82AT7Pgy9H5X9vZ8bnDvADNaWrM8EP8XSe771+VaAssTlSC5FZDh4BkEQ9U/VJkDv7T99VB1z7YCrVjfHuU1XVbmYO9Uh5NQCeRYTvvOVhWSJ0ADk9RIorGBVmLPqWH2EKwM2O7Gh04q0tg23l0uyYj2FCUzhA=
  alipay_public_key: MIIBIjANBgkqhkiG9w0BAQEFAAOCAQ8AMIIBCgKCAQEAhijSRNhCUs1tdyQn79306xvSmwWErunneWbBlQRLFCsYT2Za81y0vddCfObbl6YkVpeXityTQ2BVPQwFfd7aG4+UcCEVkUrr68rhGstWcui4dE9FdHr8/Ob592n6wEgCTesem4lni9QWXI1JgYyZccsFrzPVaeLRJf4LyL7lhIWdyTt0cwV/myXmsCh4zLDezuXIbFnPqsGWpR2mPKCz6wC5yrGylyBppUSB8esD6Pu8Wdf7iahfUrj+yCcdiiKEnMUGVG2tNUlSJB+Aj4WF9SpMpiRHL9dx9Nu4A32IGcgYClOeb79o5rp0/eay2zAv3U5gmu+2R+1eYlf0ggaDcQIDAQAB
  notify_url: http://xfg-studio.natapp1.cc/api/v1/alipay/pay_notify
  return_url: https://gaga.plus
  gatewayUrl: https://openapi-sandbox.dl.alipaydev.com/gateway.do


mall-mvc:
  request:
    prefix: /mvc



weixin:
  touser: or0Ab6ivwmypESVp_bYuk92T6SvU
  template_id: GLlAM-Q4jdgsktdNd35hnEbHVam2mwsW2YWuxDhpQkU
  url: https://weixin.qq.com
